name: Run Sancus examples
on:
  push:
  pull_request:
  # trigger a cron job every monday at 8am
  schedule:
    - cron: '00 08 * * MON'

jobs:
  matrix-gen:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2
      - id: list_dirs
        run: |
          MATRIX=$(ls -d */ | sed 's:/*$::' | jq -cnR '[inputs | select(length>0)]')
          echo $MATRIX
          echo "::set-output name=matrix::$MATRIX"

  test-examples:
    name: ${{ matrix.example }} on sancus-devel-${{ matrix.sancus-security}}${{ matrix.availability == 1 && '-aion' || '' }}
    runs-on: ubuntu-latest
    needs: matrix-gen
    container:
      # sancus-devel Docker container is regularly built and published in the sancus-main Action Workflow
      image: docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-${{ matrix.sancus-security }}${{ matrix.availability == 1 && '-aion' || '' }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        example: ${{fromJson(needs.matrix-gen.outputs.matrix)}}
        sancus-security: [64, 128]
        availability: [0,1]
        # use include
        include:
          - example: hello-library
            flags: ARCHIVE_MODE=thin
            sancus-security: 64
          - example: hello-library
            flags: ARCHIVE_MODE=thick
            sancus-security: 128
        exclude:
          # exclude all aion + 128 bit for now
          - sancus-security: 128
            availability: 1
          - availability: 1
            example: confidential-loading
          - availability: 0
            example: atomic-violation

    steps:
      - uses: actions/checkout@v2
        name: Pull repository
      - run: make SANCUS_SECURITY=${{ matrix.sancus-security }} CI=1 ${{ matrix.flags }} ${{ matrix.example }}.sim
        name: Build and run ${{ matrix.example }} @ ${{ matrix.availability == 1 && 'Aion and ' || '' }}${{ matrix.sancus-security}}-bit security
